disabled_rules:
  - trailing_whitespace
  - line_length
  - file_length
  - type_body_length
  - function_body_length

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - sorted_first_last
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

excluded:
  - Tests
  - Example
  - .build
  - DerivedData
  
identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
    
function_parameter_count:
  warning: 6
  error: 8
  
cyclomatic_complexity:
  warning: 15
  error: 20

reporter: "xcode"